architect:
  - iizudev
assets:
  crates-io.env: "iizudev/.rultor#crates-io.env"
install: |
  source /home/r/crates-io.env
release:
  script: |
    [[ "${tag}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
    VERSION="${tag#v}"
    git checkout -b "release-${tag}"

    sed -i.bak "s/^version = .*/version = \"${VERSION}\"/" Cargo.toml && rm Cargo.toml.bak
    grep -q "version = \"${VERSION}\"" Cargo.toml

    git add Cargo.toml
    git commit -m "bump version to ${VERSION}"

    git checkout main
    git merge --no-ff "release-${tag}" -m "release ${VERSION}"
