docker:
  image: rust:alpine
release:
  script: |
    apk add --no-cache sed

    git checkout -b "release-${tag}"

    if [[ ! "${tag}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "❌ Tag '${tag}' must be semantic (e.g., v1.2.3)"
      exit 1
    fi

    TARGET_VERSION="${tag#v}"  # Strips 'v' prefix

    sed -i.bak "s/^version = .*/version = \"${TARGET_VERSION}\"/" Cargo.toml && rm Cargo.toml.bak
    if ! grep -q "version = \"${TARGET_VERSION}\"" Cargo.toml; then
      echo "❌ Failed to update Cargo.toml version"
      exit 1
    fi

    git add Cargo.toml
    git commit -m "bump version to ${TARGET_VERSION}"
    git tag -a "${tag}" -m "release ${tag}"

    git checkout main
    git merge --no-ff "release-${tag}" -m "release ${RELEASE_VERSION}"
    git push origin main "v${RELEASE_VERSION}"
